### ISSUE TITLE
Project summary

### ISSUE THREAD

**Issue by sanykey** [hexlet-volunteers/interviews#2]
# Общая идея
- Сделать небольшой сайт на котором одни записываются как "Cобеседующий", а другие как "хочу собеседоваться".
- Когда заходишь на сайт там две больших кнопки. Одна "хочу собеседовать", тыкаешь,заполняешь форму (город, должность и где работает) и ждешь писем. Другие тыкают “хочу собеседоваться" (город, по каким языкам)
- В идеале прямо на этом же сайте эти собеседования организовывать.
- Можно прикрутить на сайт тотализатор
- Сделайте авторизацию только через гитхаб, запрашивать у гитхаба nickname/email
# Технологии:
## Бекенд
- nodejs
- expressjs
- postgresql
- es6
- babel
- async
- await
- тесты mocha и интеграция с travis-ci
## Фронтенд:
- bootstrap
- postcss
## Рабочее окружение
- eslint - настроить в редакторе
- Vagrantfile + ansible playbook
# Еще заметки
- на хероку выложить и мы сможем его попиарить, а потом будем эту информацию использовать для наших собеседований
  сделать без разницы на чем
- весь код пулреквестами. Пулреквест принимается только если хотя бы двое ментейнеров сказали “ок”, в нашем случае их собственно два).
- первая версия это не настоящий продакшен

Первоначальный план задач:
- [x] конфиг бабеля(пресеты) #22 - @alexander37137 
- [x] конфиг postcss(плагины?) #23 - @alexander37137 
- [x] морда на бутстрапе #26 - ваш покорный слуга
- [x] авторизация через гитхаб #51 - @Shamash2014 
- [x] конфиг постгри (?) + запись в базу - #50 @gldmtr 
- [x] добавить окружение для тестов (?) #24 - @Nitive  

P.S. Пишем комментарии к коммитам и PR на английском, остальное на русском.

**Comment by sashashakun** [comment]
Мне видится такой пул задач:

- [ ] конфиг бабеля(пресеты)
- [ ] конфиг postcss(плагины?)
- [ ] морда на бутстрапе
- [ ] настройка деплоя на хероку
- [ ] авторизация через гитхаб
- [ ] конфиг постгри (?)

Идея, предложения, осуждения?

**Comment by sashashakun** [comment]
Небольшое дополнение, пишем комментарии к коммитам и PR на английском, остальное на русском.

**Comment by sashashakun** [comment]
Closed as a mentioned tasks are closed
